---
title: "Miraculous Maurice"
---

#A Brief Introduction to the Life and Times of Maurice 


Maurice was a fish acquired from [Walmart.](https://www.walmart.com/cp/fish/202074) At the time of his adoption, he was roughly one inch by one inch. By the time of his death (RIP Maurice), he had grown to be the size of an adult human's palm. You could say he was the Clifford of fish. 

General fish characteristics  | Characteristics specific to Maurice
------------------------------|-------------------------------------------------
Fins                          | Fins as translucent and pretty as delicate fans
Mouth                         | Kissy-face mouth 
Scales                        | Scales that allowed for the inspection of veins

###An unordered list of example reasons to love Maurice:
* He was beautiful
   + Pink scales
   + Large eyes
* He could swim backwards 
* He was a real crowd-pleaser with a sparkling personality  
 
Maurice lived to be 8+ years old. 

~~He pillaged the tank and was suspected, on multiple occasions, of murder.~~ 

**He had a heart of gold.** 

###A sample list of fish Maurice outlived, in the order that they died: 
1. Paula, fellow pink gourami 
2. Bubbles, a pincher fish who was banished from the tank for obscene violence
3. The Cashmere Sisters, twin angel fish 
    + Kelly
    + Clarkson
    
In the great fish tank filter bust of 2015, he was the *only* soul to **escape** the massacre. 

He died in 2017, while I was away. He was buried in the garden by my mother. 

> Long live Maurice. 
